---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pizza-web-service
spec:
  selector:
    app: nginx-web-pizza
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pizza-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web-pizza
  template:
    metadata:
      labels:
        app: nginx-web-pizza
    spec:
      containers:
      - name: cont-pizza
        image: nicoss0013/restaurants:pizzav2
        ports:
        - containerPort: 80
